# Generated by Django 4.1.2 on 2023-01-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('last_modified', models.DateTimeField()),
                ('last_modifier', models.CharField(max_length=30)),
            ],
        ),
    ]
