# Generated by Django 4.1.2 on 2023-01-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='first_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='last_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='username',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
    ]
